name: Build and Deploy Vite.js Frontend to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: admin-portal
  ACR_NAME: govconn
  CONTAINER_APP_NAME: govconn-portal
  RESOURCE_GROUP: rootcode
  ACR_LOGIN_SERVER: govconn.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SECRETS }}

      # 3. Log in to Azure Container Registry (ACR)
      - name: Azure ACR Login
        run: az acr login --name ${{ env.ACR_NAME }}

      # 4. Create .env for build-time variables
      - name: Create .env File with Secrets
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env
          echo ".env file created successfully."

      # 5. Build and Push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      # 6. Deploy to Azure Container Apps
      - name: Deploy New Image to Azure Container App
        run: |
          IMAGE_TAG=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $IMAGE_TAG
